### ISSUE TITLE
in-app messaging does not work

### ISSUE THREAD

**Issue by ferrous777** [pushio/PushIOManager_iOS#7]

**Comment by HiroProt** [comment]
Can you please share your curl (minus the sender secret) to reproduce the issue?

**Comment by ferrous777** [comment]
curl "https://manage.pushio.com/api/v1/notify_devices/VwO9C49cuw/SENDER_SECRET" ‐d 'recipient_ids={ "VwO9C49cuw_sY7g": [ "0d9e11ab4557ed3dba9cc758098b38d2af7f89db41362a7cee4a8e2cda7d89dc" ] }&payload=%7B%22payload_apns%22%3A%20%7B%22aps_extra%22%3A%20%7B%22content‐available%22%3A%201%7D%2C%20%22extra%22%3A%20%7B%22p_event_action%22%3A%20%7B%22event_type%22%3A%20%22%24ExplicitAppOpen%22%2C%20%22start_ts%22%3A%20%222014‐03‐19T19%3A04%3A18Z%22%2C%20%22expiry_ts%22%3A%20%222016‐03‐25T23%3A00%3A00%2B05%3A30%22%2C%20%22action_uri%22%3A%20%22pio‐VwO9C49cuw%3A%2F%2Fshow_iam%3Fstyle%3Dfullscreen%26html%3D%253Ca%2520href%253D%2522http%253A%252F%252Foracle.com%2522%253Eoracle.com%253C%252Fa%253E%22%7D%7D%7D%7D'

**Comment by ferrous777** [comment]
and when using push io manage page:

sending this:

{"p_event_action":{"event_type":"$ExplicitAppOpen","start_ts":"2014‐03‐19T19:04:18Z","expiry_ts":"2016‐03‐25T23:00:00+05:30","action_uri":"pio‐VwO9C49cuw://show_iam?style=fullscreen&html=%3Ca%20href%3D%22http%3A%2F%2Foracle.com%22%3Eoracle.com%3C%2Fa%3E"}}

causes this:

[PushIOManager] Failed to interpret push payload: {
    "PUSHIO_RESULT_COMPL_ARG" = 0;
    "PUSHIO_RESULT_COMPL_HANDLER" = "<__NSMallocBlock__: 0x170250860>";
    aps =     {
        alert = "test in-app";
    };
    ei = VwO9C49cuw8556189836576rzrp;
    "p_event_action" =     {
        "action_uri" = "pio\U2010VwO9C49cuw://show_iam?style=fullscreen&html=%3Ca%20href%3D%22http%3A%2F%2Foracle.com%22%3Eoracle.com%3C%2Fa%3E";
        "event_type" = "$ExplicitAppOpen";
        "expiry_ts" = "2016\U201003\U201025T23:00:00+05:30";
        "start_ts" = "2014\U201003\U201019T19:04:18Z";
    };
}

**Comment by HiroProt** [comment]
Thanks!

Let us try to reproduce here on our end. Could you also send me a screenshot of the 404 error you're getting?

**Comment by ferrous777** [comment]
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
</head>

<body>
  
  <div class="dialog">
    <h1>The page you were looking for doesn't exist.</h1>
    <p>You may have mistyped the address or the page may have moved.</p>
  </div>
</body>
</html>
curl: (6) Could not resolve host: ‐d
curl: (3) [globbing] nested brace in column 36

**Comment by HiroProt** [comment]
I think there is something going on with your curl command (notice the globbing error, and it trying to interpret -d as the hostname.

I also noticed that your recipient_id looks like an iOS device token, instead of a Push IO device ID. Device IDs look like this:

590FBE4C-793E-4814-A8CD-89DC432F0D94

Let me do a little bit more digging, but maybe this helps.

**Comment by ferrous777** [comment]
i tried with and without that device id, same story both ways.

**Comment by HiroProt** [comment]
Ok, looks like your -d is the culprit. For some reason, it's a weird Unicode dash that curl doesn't seem to like.

Try deleting and re-typing your -d on your command-line, and the curl should work.

**Comment by HiroProt** [comment]
Your payload that is giving you errors on-device has the same problem, in the date hashes and URL scheme. Here the offending hashes have been replaced by dots:

{"p_event_action":{"event_type":"$ExplicitAppOpen","start_ts":"2014•03•19T19:04:18Z","expiry_ts":"2016•03•25T23:00:00+05:30","action_uri":"pio•VwO9C49cuw://show_iam?style=fullscreen&html=%3Ca%20href%3D%22http%3A%2F%2Foracle.com%22%3Eoracle.com%3C%2Fa%3E"}}

If you got these examples from us, and they were the culprit, please let me know what the source was.

Thanks :)

**Comment by ferrous777** [comment]
the curl was successful.  is the device_id supposed to be this variable: pushIOUUID?

**Comment by HiroProt** [comment]
Yep, that's the one.

**Comment by ferrous777** [comment]
Received [ei: VwO9C49cuw8556184543602dzaV, p_event_action: {
    "action_uri" = "pio-VwO9C49cuw://show_iam?style=fullscreen&html=%3Ca%20href%3D%22http%3A%2F%2Foracle.com%22%3Eoracle.com%3C%2Fa%3E";
    "event_type" = "$ExplicitAppOpen";
    "expiry_ts" = "2016-03-25T23:00:00+05:30";
    "start_ts" = "2014-03-19T19:04:18Z";
}, aps: {
    "content-available" = 1;
}]

I call this method:

[[PushIOManager sharedInstance] didReceiveRemoteNotification:userInfo fetchCompletionResult:UIBackgroundFetchResultNewData fetchCompletionHandler:completion];

and nothing happens.

if I call the deep link from a web page on the device:

[PushIOManager] Failed to open URL 'pio-vwo9c49cuw://show_iam?style=fullscreen&html=%3Ca%20href%3D%22http%3A%2F%2Foracle.com%22%3Eoracle.com%3C%2Fa%3E'

this happens.
