### ISSUE TITLE
Track Custom Metric

### ISSUE THREAD

**Issue by onurvarrrr** [pushio/PushIOManager_iOS#9]
I see in https://github.com/pushio/PushIOManager_iOS/blob/master/PushIOManager.framework/Versions/A/Headers/PushIOManager.h

there is method called : 
- (void) trackEngagementCustomMetric:(NSString *)customMetric;

I've sent some CustomMetrics (which are NSString) but couldn't see them in PushIO Dashboards or history or analytics.

Can you please help to find these custom metrics ?
Thanks

**Comment by HiroProt** [comment]
Hi @onurvarrrr,

Could you please direct your question to My Oracle Support?

https://support.oracle.com
